# Generated by Django 3.2.15 on 2022-08-22 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortname', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('phonecode', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'demo_country',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(error_messages={'required': 'UserName is required', 'unique': 'UserName is already exists'}, max_length=210, unique=True)),
                ('password', models.CharField(max_length=1000)),
                ('password2', models.CharField(max_length=1000)),
                ('first_name', models.CharField(max_length=1000)),
                ('last_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('phone', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.CharField(error_messages={'unique': 'Email has already been Registered'}, max_length=64, unique=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='country', to='app_demo.country')),
            ],
            options={
                'db_table': 'demo_user',
            },
        ),
    ]
