# Generated by Django 3.2.15 on 2022-08-26 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0002_user_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password2',
        ),
    ]
