# Generated by Django 3.2.15 on 2022-09-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0009_auto_20220901_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='user', max_length=256),
        ),
    ]
