# Generated by Django 3.2.15 on 2022-09-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0010_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('n', 'non-binary'), ('u', 'Prefer Not To Say')], default='m', max_length=50, verbose_name='gender'),
        ),
    ]
