# Generated by Django 3.2.15 on 2022-09-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0016_alter_mood_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='date',
            field=models.DateField(auto_now=True, error_messages={'unique': 'You already submitted response'}, unique=True),
        ),
    ]
