# Generated by Django 3.2.15 on 2022-09-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0017_alter_mood_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
