# Generated by Django 3.2.15 on 2022-09-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0018_alter_mood_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mood',
            table='mood_table',
        ),
    ]
