# Generated by Django 3.2.15 on 2022-08-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0004_templatemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTemp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=64)),
                ('verification_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_temp',
            },
        ),
    ]
