# Generated by Django 3.2.15 on 2022-08-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0005_usertemp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertemp',
            name='verification_code',
            field=models.IntegerField(default=255252),
            preserve_default=False,
        ),
    ]
