# Generated by Django 3.2.15 on 2022-09-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0006_alter_usertemp_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=210, null=True),
        ),
    ]
