# Generated by Django 3.2.15 on 2022-09-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0013_rename_userid_contactus_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='username',
            new_name='userid',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='user', max_length=256, unique=True),
        ),
    ]
